name: library

services:
  postgres:
    image: postgres:16
    container_name: library_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: library_dev
      POSTGRES_PASSWORD: library_dev_password
      POSTGRES_DB: library_alberto_gutierrez_botero
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
